<?php

/**
 * @file
 * Islandora archive solution pack module
 */

/**
 * Islandora archive sp required fedora objects
 *
 * @return type
 */

function islandora_archive_sp_required_fedora_objects() {

  // Add the form and associate it to the content model
  $model_path = drupal_get_path('module', 'islandora_archive_sp');
  $form_name = 'Islandora Archive MODS Form';
  $form_xml = file_get_contents("$module_path/xml/mods_archive.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp_basic_archive', $form_name);

  return array(
    'islandora_archive_sp' => array(
      'module' => 'islandora_archive_sp',
      'title' => 'Islandora Archive Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_archive',
          'label' => 'Islandora archive content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/ARCHIVE_SP_CMODEL.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:sp_archive_collection',
          'label' => 'Islandora Archive Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_mimetype_tar.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datasream_file' => "$module_path/xml/ARCHIVE-COLLECTION_POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}
