<?php

/**
 * @file
 * Islandora web archive solution pack module
 */

/**
 * Islandora web archive sp required fedora objects
 *
 * @return type
 */

function islandora_web_archive_sp_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  // Add the form and associate it to the content model
  $module_path = drupal_get_path('module', 'islandora_web_archive_sp');
  $form_name = 'Islandora Web ARChive MODS Form';
  $form_xml = file_get_contents("$module_path/xml/mods_web_archive.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp_web_archive', $form_name);

  return array(
    'islandora_web_archive_sp' => array(
      'module' => 'islandora_web_archive_sp',
      'title' => 'Islandora Web ARChive Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_web_archive',
          'label' => 'Islandora Web ARCchive content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/WEB_ARCHIVE-COLLECTION_POLICY.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:sp_web_archive_collection',
          'label' => 'Islandora Web ARChive Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/WEB_ARCHIVE-COLLECTION_POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}
